services:
  ### Traefik reverse proxy
  traefik:
    image: traefik:v3.0
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"            # Reverse proxy public
      - "${TRAEFIK_PORT}:8080"        # Dashboard (optionnel)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - backend

  ### Gateway (auth, routing)
  gateway:
    build:
      context: ./amazing_gateway
    ports:
      - "${GATEWAY_PORT}:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.gateway.entrypoints=web"
      - "traefik.http.services.gateway.loadbalancer.server.port=8080"
    networks:
      - backend
      - db
    depends_on:
      - mariadb
      - redis
      - form
      - review
    environment:
      - GATEWAY_PORT=${GATEWAY_PORT}
      - REVIEW_HOST=review
      - REVIEW_PORT=${REVIEW_PORT}
      - FORM_HOST=form
      - FORM_PORT=${FORM_PORT}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_PORT=${MARIADB_PORT}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - REDIS_URL=${REDIS_URL}

  ### Microservice Form
  form:
    build:
      context: ./amazing_form
    expose:
      - "${FORM_PORT}"
    depends_on:
      - mariadb
    networks:
      - backend
      - db
    labels:
      - "traefik.enable=false"
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_PORT=${MARIADB_PORT}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}

  ### Microservice Review
  review:
    build:
      context: ./amazing_review
    expose:
      - "${REVIEW_PORT}"
    depends_on:
      - mariadb
    networks:
      - backend
      - db
    labels:
      - "traefik.enable=false"
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_PORT=${MARIADB_PORT}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}

  ### Base de données MariaDB
  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - amazing_data:/var/lib/mysql
    networks:
      - db

  ### Redis
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - backend

  ### PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "${PMA_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - db

networks:
  backend:
  db:

volumes:
  amazing_data: